POST http://localhost:9113/V3/StudentNames/SubTableOnObj/Alter/WithPk/{RowPk}/{KeyName}/{pk}
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "email": "",
  "CollegeName": "",
  "Country": "",
  "EntranceRank": "",
  "YearPassOut": "",
  "Back_logs": "",
  "RollNumber": "",
  "file": "",
  "GitLink": ""
}